### ISSUE TITLE
change issue_id to issue_number

### ISSUE THREAD

**Issue by kjaymiller** [Python-Community-News/GH-Issues#6]
Instead of `issue_id` (which is a thing in the api) this value should be `issue_number` which directly correlates to the `number` attribute in the issue.  (e.g if this is issue #6 then `issue._number == 6`") 

https://github.com/Python-Community-News/GH-Issues/blob/3484064721da0b04d85b13bfa3d76fabe4c45884/src/gh_issues/__init__.py#L40

**Comment by Farhan-Ali2002** [comment]
so basically we just have to replace issue_id with issue_number or did I misinterpret it?

**Comment by kjaymiller** [comment]
Sorry there is a PR #15 that addresses this already.
