### ISSUE TITLE
add pip install pre-commit 

### ISSUE THREAD

**Issue by blulady** [Python-Community-News/GH-Issues#9]
In the [CONTRIBUTING.md](https://github.com/Python-Community-News/GH-Issues/blob/main/CONTRIBUTING) on line 92 (in parenthesis), add in  "or `pip install pre-commit`".

**Comment by kjaymiller** [comment]
I hope you haven't jumped on this one yet...  #7 kinda resolved it behind the scenes in a future update (It will be added to `requirements.dev`). That said the the contributing docs will need that segment removed. I can leave you to that part if you don't mind?
